mongo:
  config:
    replicaSetName:
    type: INSTANCE
    connectTimeout: 3000
    socketTimeout: 3000
    serverTimeout: 3000
    retryProperties:
      retryBackOffTime: 5000
      retryMaxAttempts: 3

server:
  port: 8080

cxf:
  path: /checkMeIn/v1